name: Build docs

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [16]

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: "npm"

      - name: Install night-owl dependencies
        run: npm ci

      - name: Install night-owl
        run: npm ci
        working-directory: ./docs

      - name: Build site
        run: npm run build
        working-directory: ./docs

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./docs/dist
          github_token: ${{ secrets.GITHUB_TOKEN }}
